### ISSUE TITLE
Does not generate files? 

### ISSUE THREAD

**Issue by ignatandrei** [ladeak/ProtobufSourceGenerator#17]
I maintain a list of Roslyn Source Code Generators at https://ignatandrei.github.io/RSCG_Examples/v2/docs/List-of-RSCG

I am trying to make an example with this nuget package

The branch is https://github.com/ignatandrei/RSCG_Examples/tree/111-protobuf and the solution is at
<RSCG_Examples>\v2\rscg_examples\ProtobufSourceGenerator\src\ProtobufSourceGenerator.sln

Even I have put 
```xml

	<PropertyGroup>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)\GX</CompilerGeneratedFilesOutputPath>
	</PropertyGroup>
```

the files are not generated.
What I am doing wrong ? 
Thanks

**Comment by ladeak** [comment]
Could you try updating the version to 1.5.1 please?

**Comment by ignatandrei** [comment]
Now it is ok, thanks
https://ignatandrei.github.io/RSCG_Examples/v2/docs/ProtobufSourceGenerator

**Comment by ladeak** [comment]
Thank you for pointing out, I was using an internal nuget repo, where the issue has not escalated.
